Chaste: ArchiveOpener< OutputArchive, std::ofstream > Class Template Reference
ArchiveOpener< OutputArchive, std::ofstream > Class Template Reference
Partial class specialization to specialize class members for output archives.
Public Member Functions
ArchiveOpener (const FileFinder &rDirectory, const std::string &rFileNameBase, unsigned procId)
OutputArchive * GetCommonArchive ()
Private Attributes
std::ofstream * mpCommonStream
std::ofstream * mpPrivateStream
OutputArchive * mpCommonArchive
OutputArchive * mpPrivateArchive
Friends
class TestArchivingHelperClasses
Detailed Description
template<class OutputArchive>
class ArchiveOpener< OutputArchive, std::ofstream >
Partial class specialization to specialize class members for output archives.
Template Parameters
OutputArchive Type of the output archive type, which can vary between text and binary output archives from boost::archive
Definition at line 163 of file ArchiveOpener.cpp.
Constructor & Destructor Documentation
ArchiveOpener()
template<class OutputArchive > ArchiveOpener< OutputArchive, std::ofstream >::ArchiveOpener (const FileFinder & rDirectory, const std::string & rFileNameBase, unsigned procId) inline
Specialization for output archives.
Parameters
rDirectory
rFileNameBase
procId
Definition at line 175 of file ArchiveOpener.cpp.
References PetscTools::AmMaster(), EXCEPTION, ArchiveLocationInfo::GetArchiveDirectory(), ArchiveLocationInfo::GetArchiveRelativePath(), ArchiveLocationInfo::GetIsDirRelativeToChasteTestOutput(), PetscTools::GetMyRank(), ArchiveLocationInfo::GetProcessUniqueFilePath(), ArchiveOpener< Archive, Stream >::mpCommonArchive, ArchiveOpener< Archive, Stream >::mpCommonStream, ArchiveOpener< Archive, Stream >::mpPrivateArchive, ArchiveOpener< Archive, Stream >::mpPrivateStream, ProcessSpecificArchive< Archive >::Set(), and ArchiveLocationInfo::SetArchiveDirectory().
~ArchiveOpener()
template<class OutputArchive > ArchiveOpener< OutputArchive, std::ofstream >::~ArchiveOpener () inline
Definition at line 251 of file ArchiveOpener.cpp.
Member Function Documentation
GetCommonArchive()
template<class OutputArchive > OutputArchive * ArchiveOpener< OutputArchive, std::ofstream >::GetCommonArchive () inline
Returns
the main archive for replicated data.
Definition at line 245 of file ArchiveOpener.cpp.
References ArchiveOpener< Archive, Stream >::mpCommonArchive.
Friends And Related Symbol Documentation
TestArchivingHelperClasses
template<class OutputArchive > friend class TestArchivingHelperClasses friend
Definition at line 166 of file ArchiveOpener.cpp.
Member Data Documentation
mpCommonArchive
template<class OutputArchive > OutputArchive* ArchiveOpener< OutputArchive, std::ofstream >::mpCommonArchive private
The main archive.
Definition at line 275 of file ArchiveOpener.cpp.
mpCommonStream
template<class OutputArchive > std::ofstream* ArchiveOpener< OutputArchive, std::ofstream >::mpCommonStream private
The file stream for the main archive.
Definition at line 269 of file ArchiveOpener.cpp.
mpPrivateArchive
template<class OutputArchive > OutputArchive* ArchiveOpener< OutputArchive, std::ofstream >::mpPrivateArchive private
The secondary archive.
Definition at line 278 of file ArchiveOpener.cpp.
mpPrivateStream
template<class OutputArchive > std::ofstream* ArchiveOpener< OutputArchive, std::ofstream >::mpPrivateStream private
The file stream for the secondary archive.
Definition at line 272 of file ArchiveOpener.cpp.
The documentation for this class was generated from the following file:
global/src/checkpointing/ArchiveOpener.cpp