Chaste: ArchiveOpener< InputArchive, std::ifstream > Class Template Reference
ArchiveOpener< InputArchive, std::ifstream > Class Template Reference
Partial class specialization to specialize class members for input archives.
Public Member Functions
ArchiveOpener (const FileFinder &rDirectory, const std::string &rFileNameBase, unsigned procId)
InputArchive * GetCommonArchive ()
Private Attributes
std::ifstream * mpCommonStream
std::ifstream * mpPrivateStream
InputArchive * mpCommonArchive
InputArchive * mpPrivateArchive
Friends
class TestArchivingHelperClasses
Detailed Description
template<class InputArchive>
class ArchiveOpener< InputArchive, std::ifstream >
Partial class specialization to specialize class members for input archives.
Template Parameters
InputArchive Type of the input archive type, which can vary between text and binary input archives from boost::archive
Definition at line 57 of file ArchiveOpener.cpp.
Constructor & Destructor Documentation
ArchiveOpener()
template<class InputArchive > ArchiveOpener< InputArchive, std::ifstream >::ArchiveOpener (const FileFinder & rDirectory, const std::string & rFileNameBase, unsigned procId) inline
Specialization for input archives.
Parameters
rDirectory
rFileNameBase
procId
Definition at line 69 of file ArchiveOpener.cpp.
References EXCEPTION, ArchiveLocationInfo::GetArchiveDirectory(), ArchiveLocationInfo::GetProcessUniqueFilePath(), ArchiveOpener< Archive, Stream >::mpCommonArchive, ArchiveOpener< Archive, Stream >::mpCommonStream, ArchiveOpener< Archive, Stream >::mpPrivateArchive, ArchiveOpener< Archive, Stream >::mpPrivateStream, ProcessSpecificArchive< Archive >::Set(), and ArchiveLocationInfo::SetArchiveDirectory().
~ArchiveOpener()
template<class InputArchive > ArchiveOpener< InputArchive, std::ifstream >::~ArchiveOpener () inline
Definition at line 134 of file ArchiveOpener.cpp.
Member Function Documentation
GetCommonArchive()
template<class InputArchive > InputArchive * ArchiveOpener< InputArchive, std::ifstream >::GetCommonArchive () inline
Returns
the main archive for replicated data.
Definition at line 128 of file ArchiveOpener.cpp.
References ArchiveOpener< Archive, Stream >::mpCommonArchive.
Friends And Related Symbol Documentation
TestArchivingHelperClasses
template<class InputArchive > friend class TestArchivingHelperClasses friend
Definition at line 60 of file ArchiveOpener.cpp.
Member Data Documentation
mpCommonArchive
template<class InputArchive > InputArchive* ArchiveOpener< InputArchive, std::ifstream >::mpCommonArchive private
The main archive.
Definition at line 151 of file ArchiveOpener.cpp.
mpCommonStream
template<class InputArchive > std::ifstream* ArchiveOpener< InputArchive, std::ifstream >::mpCommonStream private
The file stream for the main archive.
Definition at line 145 of file ArchiveOpener.cpp.
mpPrivateArchive
template<class InputArchive > InputArchive* ArchiveOpener< InputArchive, std::ifstream >::mpPrivateArchive private
The secondary archive.
Definition at line 154 of file ArchiveOpener.cpp.
mpPrivateStream
template<class InputArchive > std::ifstream* ArchiveOpener< InputArchive, std::ifstream >::mpPrivateStream private
The file stream for the secondary archive.
Definition at line 148 of file ArchiveOpener.cpp.
The documentation for this class was generated from the following file:
global/src/checkpointing/ArchiveOpener.cpp